INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_TYPE, HOST_NAME, PORT, DATABASE_NAME, USER_NAME, PASSWORD, FILE_PATH, API_ENDPOINT, SECURITY_PROTOCOL, AUTH_METHOD, CONNECTION_PARAMETERS, CREATED_TIME, UPDATED_TIME, DESCRIPTION, ACTIVE_FLAG) 
VALUES ('AMAZON', 'JSON', NULL, NULL, NULL, NULL, NULL, '\Setup\JSON_Setup\Amazon_csd_data.json', NULL, NULL, NULL, '{"format":"json","schema":"customer_support"}', NOW(), '2999-12-31 00:00:00', 'Amazon Customer support JSON data.', 'Y');

COMMIT;

INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_TYPE, HOST_NAME, PORT, DATABASE_NAME, USER_NAME, PASSWORD, FILE_PATH, API_ENDPOINT, SECURITY_PROTOCOL, AUTH_METHOD, CONNECTION_PARAMETERS, CREATED_TIME, UPDATED_TIME, DESCRIPTION, ACTIVE_FLAG) 
VALUES ('UBER', 'XML', NULL, NULL, NULL, NULL, NULL, '\Setup\XML_Setup\Uber_csd_data.xml', NULL, NULL, NULL, '{"schema":"customer_support","namsepace":"CSD"}', NOW(), '2999-12-31 00:00:00', 'Uber Customer support XML data.', 'Y');

COMMIT;

INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_TYPE, HOST_NAME, PORT, DATABASE_NAME, USER_NAME, PASSWORD, FILE_PATH, API_ENDPOINT, SECURITY_PROTOCOL, AUTH_METHOD, CONNECTION_PARAMETERS, CREATED_TIME, UPDATED_TIME, DESCRIPTION, ACTIVE_FLAG) 
VALUES ('AT&T', 'CSV', NULL, NULL, NULL, NULL, NULL, '\Setup\CSV_Setup\ATT_csd_data.xml', NULL, NULL, NULL, '{"delimiter":"|","header":true}', NOW(), '2999-12-31 00:00:00', 'AT&T Customer support CSV data.', 'Y');

COMMIT;

INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_TYPE, HOST_NAME, PORT, DATABASE_NAME, USER_NAME, PASSWORD, FILE_PATH, API_ENDPOINT, SECURITY_PROTOCOL, AUTH_METHOD, CONNECTION_PARAMETERS, CREATED_TIME, UPDATED_TIME, DESCRIPTION, ACTIVE_FLAG) 
VALUES ('CSD_DASHBOARD', 'RDBMS', '192.168.1.10', 5432, 'csd_database', 'csd_user', 'Csd_password@123', NULL, NULL, 'SSL', 'Basic', '{"schema":"public"}', NOW(), '2999-12-31 00:00:00', 'Relational database for storing the transformed data to perform EDA and Visualization.', 'Y');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('John', 'A.', 'Doe', 'JDoe', 'AMAZON', '2023-01-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Jane', 'B.', 'Smith', 'JSmith', 'AMAZON', '2023-02-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Alice', 'C.', 'Johnson', 'AJohnson', 'AMAZON', '2023-03-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Bob', 'D.', 'Williams', 'BWilliams', 'AMAZON', '2023-04-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Charlie', 'E.', 'Brown', 'CBrown', 'AMAZON', '2023-05-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('David', 'F.', 'Jones', 'DJones', 'AMAZON', '2023-06-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Eve', 'G.', 'Garcia', 'EGarcia', 'AMAZON', '2023-07-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Frank', 'H.', 'Martinez', 'FMartinez', 'AMAZON', '2023-08-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Grace', 'I.', 'Hernandez', 'GHernandez', 'AMAZON', '2023-09-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Hank', 'J.', 'Lopez', 'HLopez', 'AMAZON', '2023-10-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Ivy', 'K.', 'Gonzalez', 'IGonzalez', 'UBER', '2023-11-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Jack', 'L.', 'Wilson', 'JWilson', 'UBER', '2023-12-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Kara', 'M.', 'Anderson', 'KAnderson', 'UBER', '2023-01-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Leo', 'N.', 'Thomas', 'LThomas', 'UBER', '2023-02-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Mia', 'O.', 'Taylor', 'MTaylor', 'UBER', '2023-03-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Nate', 'P.', 'Moore', 'NMoore', 'UBER', '2023-04-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Olivia', 'Q.', 'Jackson', 'OJackson', 'UBER', '2023-05-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Paul', 'R.', 'White', 'PWhite', 'UBER', '2023-06-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Quinn', 'S.', 'Harris', 'QHarris', 'UBER', '2023-07-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Ryan', 'T.', 'Martin', 'RMartin', 'UBER', '2023-08-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Sara', 'U.', 'Thompson', 'SThompson', 'AT&T', '2023-09-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Tom', 'V.', 'Garcia', 'TGarcia', 'AT&T', '2023-10-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Uma', 'W.', 'Martinez', 'UMartinez', 'AT&T', '2023-11-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Victor', 'X.', 'Hernandez', 'VHernandez', 'AT&T', '2023-12-15 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Wendy', 'Y.', 'Lopez', 'WLopez', 'AT&T', '2023-01-20 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Xander', 'Z.', 'Gonzalez', 'XGonzalez', 'AT&T', '2023-02-20 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Yara', 'A.', 'Wilson', 'YWilson', 'AT&T', '2023-03-20 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Zane', 'B.', 'Anderson', 'ZAnderson', 'AT&T', '2023-04-20 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Abby', 'C.', 'Thomas', 'AThomas', 'AT&T', '2023-05-20 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSUEDO_NAME, SUPPORT_TEAM, START_DATE, END_DATE)
VALUES ('Edgar', 'D.', 'Jones', 'EDJones', 'AT&T', '2022-04-01 08:00:00', '2999-12-31 17:00:00');

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), INTERACTION_ID, SOURCE_SYSTEM_IDENTIFIER, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_ID, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), SUPPORT_CATEGORY, SUPPORT_AREA, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SUPPORT_CATEGORY, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), AGENT_PSUEDO_NAME, AGENT_ID, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), (SELECT AGENT_ID FROM CSD_AGENTS WHERE PSUEDO_NAME = AGENT_PSUEDO_NAME AND SOURCE_ID = (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON')), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), CONTACT_DATE, INTERACTION_DATE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TO_DATE(CONTACT_DATE, 'DD/MM/YYYY HH:MI:SS'), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TYPE_OF_CUSTOMER, CUSTOMER_TYPE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TYPE_OF_CUSTOMER, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), INTERACTION_DURATION, HANDLE_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_DURATION, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TOTAL_TIME, WORK_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TOTAL_TIME, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), STATUS_OF_CUSTOMER_INCIDENT, QUERY_STATUS, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), STATUS_OF_CUSTOMER_INCIDENT, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), RESOLVED_IN_FIRST_CONTACT, FIRST_CONTACT_RESOLUTION, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CASE WHEN RESOLVED_IN_FIRST_CONTACT = 'YES' THEN 'TRUE' ELSE 'FALSE' END, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), SOLUTION_TYPE, RESOLUTION_CATEGORY, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SOLUTION_TYPE, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), RATING, CUSTOMER_RATING, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CEIL(RATING/2), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), SUPPORT_IDENTIFIER, SOURCE_SYSTEM_IDENTIFIER, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_ID, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), CONTACT_REGARDING, SUPPORT_AREA, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SUPPORT_CATEGORY, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), AGENT_CODE, AGENT_ID, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), (SELECT AGENT_ID FROM CSD_AGENTS WHERE PSUEDO_NAME = AGENT_PSUEDO_NAME AND SOURCE_ID = (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON')), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), DATE_OF_INTERACTION, INTERACTION_DATE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TO_DATE(CONTACT_DATE, 'DD/MM/YYYY HH:MI:SS'), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), CUSTOMER_TYPE, CUSTOMER_TYPE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TYPE_OF_CUSTOMER, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), CONTACT_DURATION, HANDLE_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_DURATION, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), AFTER_CONTACT_WORK_TIME, WORK_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TOTAL_TIME, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), INCIDENT_STATUS, QUERY_STATUS, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), STATUS_OF_CUSTOMER_INCIDENT, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1ST_CONTACT_SOLVE, FIRST_CONTACT_RESOLUTION, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CASE WHEN RESOLVED_IN_FIRST_CONTACT = 'YES' THEN 'TRUE' ELSE 'FALSE' END, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TYPE_OF_RESOLUTION, RESOLUTION_CATEGORY, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SOLUTION_TYPE, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), SUPPORT_RATING, CUSTOMER_RATING, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CEIL(RATING/2), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TICKET_IDENTIFIER, SOURCE_SYSTEM_IDENTIFIER, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_ID, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), SUPPORT_CATEGORY, SUPPORT_AREA, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SUPPORT_CATEGORY, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), AGEN_NAME, AGENT_ID, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), (SELECT AGENT_ID FROM CSD_AGENTS WHERE PSUEDO_NAME = AGENT_PSUEDO_NAME AND SOURCE_ID = (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON')), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), DATE_OF_CALL, INTERACTION_DATE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TO_DATE(CONTACT_DATE, 'DD/MM/YYYY HH:MI:SS'), NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TYPE_OF_CUSTOMER, CUSTOMER_TYPE, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TYPE_OF_CUSTOMER, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), DURATION, HANDLE_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), INTERACTION_DURATION, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TOTAL_TIME, WORK_TIME, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), TOTAL_TIME, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TICKET_STATUS, QUERY_STATUS, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), STATUS_OF_CUSTOMER_INCIDENT, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), RESOLVED_IN_FIRST_CONTACT, FIRST_CONTACT_RESOLUTION, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CASE WHEN RESOLVED_IN_FIRST_CONTACT = 'YES' THEN 'TRUE' ELSE 'FALSE' END, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), RESOLUTION_CATEGORY, RESOLUTION_CATEGORY, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), SOLUTION_TYPE, NOW(), '2999-12-31 00:00:00')

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, TARGET_TABLE_NAME, TARGET_SOURCE_ID, TRANSFORMATION_RULE, START_DATE, END_DATE)
((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), RATING, CUSTOMER_RATING, CSD_DM, (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'RDBMS'), CEIL(RATING/2), NOW(), '2999-12-31 00:00:00')

COMMIT;