-- TABLE 1: CSD_SOURCES
-- AMAZON
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('AMAZON', 'FLAT FILE - JSON', 'INCREMENTAL - RECORD ID', NULL, 'CUSTOMER SUPPORT DATA FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

-- UBER
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('UBER', 'FLAT FILE - XML', 'FULL REFRESH - TIMESTAMP', NULL, 'CUSTOMER SUPPORT DATA FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

--AT&T
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('AT&T', 'FLAT FILE - CSV', 'FULL REFRESH', NULL, 'CUSTOMER SUPPORT DATA FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 2: CSD_SUPPORT_AREAS
-- AMAZON
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Order Issues', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Product Inquiries', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Shipping & Delivery', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Account & Security', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Payments & Billing', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Returns & Refunds', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Technical Support', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Promotions & Discounts', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Prime Membership', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Marketplace & Third-Party Sellers', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31')

COMMIT;


-- UBER
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Ride Issues', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Driver/Passenger Concerns', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Payments & Billing', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Safety & Security', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Account & Profile Management', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Promotions & Discount', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Driver Support', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Technical Support', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Uber Eats', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Accesibility Support', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31')

COMMIT;


-- AT&T
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Account Management', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Technical Support', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Support Outages', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('New Customer Onboarding', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Mobile & Wireless Services', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Home Services', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Promotions & Discounts', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Security & Privacy', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Business Services', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Loyalty & Retentions', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31')

COMMIT;


-- TABLE 3: CSD_AGENTS
-- AMAZON
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('John', 'A.', 'Doe', 'JDoe', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Jane', 'B.', 'Smith', 'JSmith', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Alice', 'C.', 'Johnson', 'AJohnson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Bob', 'D.', 'Williams', 'BWilliams', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Charlie', 'E.', 'Brown', 'CBrown', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('David', 'F.', 'Jones', 'DJones', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Eve', 'G.', 'Garcia', 'EGarcia', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Frank', 'H.', 'Martinez', 'FMartinez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Grace', 'I.', 'Hernandez', 'GHernandez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Hank', 'J.', 'Lopez', 'HLopez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31')

COMMIT;


-- UBER
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Ivy', 'K.', 'Gonzalez', 'IGonzalez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Jack', 'L.', 'Wilson', 'JWilson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Kara', 'M.', 'Anderson', 'KAnderson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Leo', 'N.', 'Thomas', 'LThomas', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Mia', 'O.', 'Taylor', 'MTaylor', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Nate', 'P.', 'Moore', 'NMoore', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Olivia', 'Q.', 'Jackson', 'OJackson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Paul', 'R.', 'White', 'PWhite', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Quinn', 'S.', 'Harris', 'QHarris', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Ryan', 'T.', 'Martin', 'RMartin', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31')

COMMIT;


-- AT&T
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Sara', 'U.', 'Thompson', 'SThompson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Tom', 'V.', 'Garcia', 'TGarcia', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Uma', 'W.', 'Martinez', 'UMartinez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Victor', 'X.', 'Hernandez', 'VHernandez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Wendy', 'Y.', 'Lopez', 'WLopez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Xander', 'Z.', 'Gonzalez', 'XGonzalez', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Yara', 'A.', 'Wilson', 'YWilson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Zane', 'B.', 'Anderson', 'ZAnderson', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Abby', 'C.', 'Thomas', 'AThomas', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('Edgar', 'D.', 'Jones', 'EJones', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31')

COMMIT;


-- TABLE 4: CSD_CUSTOMER_TYPES
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ()

COMMIT;


-- TABLE 12: CSD_TRANSFORMATIONS
INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, PYSPARK_EXPRESSION, TARGET_TABLE_NAME, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_ID', 'SOURCE_SYSTEM_IDENTIFIER', 'lambda x: "AMAZON-" + x', 'CSD_DATA_MART', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, PYSPARK_EXPRESSION, TARGET_TABLE_NAME, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'AGENT_PSEUDO_NAME', 'AGENT_ID', 'lambda agent_id: lookup_cad_agents(pseudo_code)', 'CSD_DATA_MART', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, PYSPARK_EXPRESSION, TARGET_TABLE_NAME, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CONTACT_DATE', 'INTERACTION_DATE', 'lambda date_string: to_timestamp(date_string, "dd/MM/yyyy HH:mm:ss")', 'CSD_DATA_MART', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TRANSFORMATIONS (SOURCE_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, PYSPARK_EXPRESSION, TARGET_TABLE_NAME, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT_CATEGORY', 'SUPPORT_AREA_ID', 'lambda date_string: to_timestamp(date_string, "dd/MM/yyyy HH:mm:ss")', 'CSD_DATA_MART', TRUE, NOW(), '2999-12-31');

COMMIT;