USE csd_database;

-- TABLE 1: CSD_SOURCES
CREATE TABLE CSD_SOURCES (
	SOURCE_ID 				INTEGER 		NOT NULL 		AUTO_INCREMENT,
	SOURCE_NAME 			VARCHAR(255) 	NOT NULL,
	SOURCE_FILE_TYPE 		TEXT			NOT NULL,
	DATA_LOAD_STRATEGY		TEXT			NOT NULL,
	LAST_LOADED_RECORD_ID	INTEGER,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY 			(SOURCE_ID),
	UNIQUE 					(SOURCE_NAME)
);


-- TABLE 2: CSD_SUPPORT_AREAS
CREATE TABLE CSD_SUPPORT_AREAS (
	SUPPORT_AREA_ID			INTEGER			NOT NULL		AUTO_INCREMENT,
	SUPPORT_AREA_NAME		TEXT			NOT NULL,
	SOURCE_ID				INTEGER			NOT NULL,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(SUPPORT_AREA_ID),
	FOREIGN KEY				(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID)
);


-- TABLE 3: CSD_AGENTS
CREATE TABLE CSD_AGENTS (
	AGENT_ID				INTEGER			NOT NULL		AUTO_INCREMENT,
	FIRST_NAME				TEXT			NOT NULL,
	MIDDLE_NAME				TEXT,
	LAST_NAME				TEXT			NOT NULL,
	PSEUDO_CODE				VARCHAR(255)	NOT NULL,
	SOURCE_ID				INTEGER			NOT NULL,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(AGENT_ID),
	UNIQUE					(PSEUDO_CODE),
	FOREIGN KEY				(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID)
);


-- TABLE 4: CSD_CUSTOMER_TYPES
CREATE TABLE CSD_CUSTOMER_TYPES (
	CUSTOMER_TYPE_ID		INTEGER			NOT NULL		AUTO_INCREMENT,
	CUSTOMER_TYPE_NAME		TEXT			NOT NULL,
	SOURCE_ID				INTEGER			NOT NULL,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(CUSTOMER_TYPE_ID),
	FOREIGN KEY				(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID)
);


-- TABLE 5: CSD_TABLE_TYPES
CREATE TABLE CSD_TABLE_TYPES (
	TABLE_TYPE_ID			INTEGER			NOT NULL		AUTO_INCREMENT,
	TABLE_TYPE_NAME			VARCHAR(255)	NOT NULL,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(TABLE_TYPE_ID),
	UNIQUE					(TABLE_TYPE_NAME)
);


-- TABLE 6: CSD_TABLE_LOAD_TYPES
CREATE TABLE CSD_TABLE_LOAD_TYPES (
	TABLE_LOAD_TYPE_ID		INTEGER			NOT NULL		AUTO_INCREMENT,
	TABLE_LOAD_TYPE_NAME	VARCHAR(255)	NOT NULL,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(TABLE_LOAD_TYPE_ID),
	UNIQUE					(TABLE_LOAD_TYPE_NAME)
);


-- TABLE 7: CSD_DATA_DICTIONARY
CREATE TABLE CSD_DATA_DICTIONARY (
	DATA_DICTIONARY_ID		INTEGER			NOT NULL		AUTO_INCREMENT,
	SOURCE_ID				INTEGER			NOT NULL,
	FIELD_NAME				TEXT			NOT NULL,
	DATA_TYPE				TEXT			NOT NULL,
	VALUES_ALLOWED			TEXT			NOT NULL,
	DESCRIPTION				TEXT,
	EXAMPLE					TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(DATA_DICTIONARY_ID),
	FOREIGN KEY				(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID)
);


-- TABLE 8: CSD_DATA_LOADS
CREATE TABLE CSD_DATA_LOADS (
	DATA_LOAD_ID			INTEGER			NOT NULL		AUTO_INCREMENT,
	LOAD_STATUS				TEXT			NOT NULL,
	LOAD_START_DATE			DATETIME		NOT NULL,
	LOAD_END_DATE			DATETIME,
	TOTAL_UPSERT_COUNT		INTEGER,
	VALID_COUNT				INTEGER,
	INVALID_COUNT			INTEGER,
	DATA_VALID_PERCENTAGE	INTEGER,
	LOAD_DURATION			TIMESTAMP,
	PRIMARY KEY				(DATA_LOAD_ID)
);


-- TABLE 9: CSD_TABLE_NAMES
CREATE TABLE CSD_TABLE_NAMES (
	TABLE_ID			INTEGER			NOT NULL		AUTO_INCREMENT,
	TABLE_NAME				VARCHAR(255)	NOT NULL,
	TABLE_TYPE_ID			INTEGER			NOT NULL,
	DESCRIPTION				TEXT,
	TABLE_LOAD_TYPE_ID		INTEGER			NOT NULL,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY 			(TABLE_ID),
	UNIQUE					(TABLE_NAME),
	FOREIGN KEY				(TABLE_TYPE_ID) REFERENCES CSD_TABLE_TYPES(TABLE_TYPE_ID),
	FOREIGN KEY				(TABLE_LOAD_TYPE_ID) REFERENCES CSD_TABLE_LOAD_TYPES(TABLE_LOAD_TYPE_ID)
);


-- TABLE 10: CSD_TABLE_COLUMNS
CREATE TABLE CSD_TABLE_COLUMNS (
	TABLE_COLUMN_ID			INTEGER			NOT NULL		AUTO_INCREMENT,
	TABLE_ID				INTEGER			NOT NULL,
	COLUMN_NAME				TEXT			NOT NULL,
	DATA_TYPE				TEXT			NOT NULL,
	FIELD_LENGTH			INTEGER,
	DESCRIPTION				TEXT,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(TABLE_COLUMN_ID),
	FOREIGN KEY				(TABLE_ID) REFERENCES CSD_TABLE_NAMES(TABLE_ID)
);


-- TABLE 11: CSD_DATA_MART
CREATE TABLE CSD_DATA_MART (
	CSD_ID						INTEGER			NOT NULL		AUTO_INCREMENT,
	SOURCE_ID					INTEGER			NOT NULL,
	SOURCE_SYSTEM_IDENTIFIER	TEXT			NOT NULL,
	AGENT_ID					INTEGER,
	INTERACTION_DATE			DATETIME,
	SUPPORT_AREA_ID				INTEGER,
	INTERACTION_STATUS			TEXT,
	INTERACTION_TYPE			TEXT,
	CUSTOMER_TYPE_ID			INTEGER,
	HANDLE_TIME					INTEGER,
	WORK_TIME					INTEGER,
	FIRST_CONTACT_RESOLUTION	BOOLEAN,
	QUERY_STATUS				TEXT,
	CUSTOMER_RATING				INTEGER,
	DATA_LOAD_ID				INTEGER			NOT NULL,
	IS_VALID_DATA				BOOLEAN			NOT NULL,
	ACTIVE_FLAG					BOOLEAN			NOT NULL,
	START_DATE					DATETIME		NOT NULL,
	END_DATE					DATETIME		NOT NULL,
	PRIMARY KEY					(CSD_ID),
	FOREIGN	KEY					(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID),
	FOREIGN KEY					(AGENT_ID) REFERENCES CSD_AGENTS(AGENT_ID),
	FOREIGN KEY					(SUPPORT_AREA_ID) REFERENCES CSD_SUPPORT_AREAS(SUPPORT_AREA_ID),
	FOREIGN KEY					(CUSTOMER_TYPE_ID) REFERENCES CSD_CUSTOMER_TYPES(CUSTOMER_TYPE_ID),
	FOREIGN KEY					(DATA_LOAD_ID) REFERENCES CSD_DATA_LOADS(DATA_LOAD_ID)
);


-- TABLE 12: CSD_TRANSFORMATIONS
CREATE TABLE CSD_TRANSFORMATIONS (
	TRANSFORMATION_ID		INTEGER			NOT NULL		AUTO_INCREMENT,
	SOURCE_ID				INTEGER			NOT NULL,
	SOURCE_COLUMN_NAME		TEXT			NOT NULL,
	TARGET_COLUMN_NAME		TEXT			NOT NULL,
	PYSPARK_EXPRESSION		TEXT			NOT NULL,
	TARGET_TABLE_NAME		TEXT			NOT NULL,
	ACTIVE_FLAG				BOOLEAN			NOT NULL,
	START_DATE				DATETIME		NOT NULL,
	END_DATE				DATETIME		NOT NULL,
	PRIMARY KEY				(TRANSFORMATION_ID),
	FOREIGN KEY				(SOURCE_ID) REFERENCES CSD_SOURCES(SOURCE_ID)
);