USE csd_database;

-- TABLE 1: CSD_SOURCES
-- AMAZON
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('AMAZON', 'FLAT FILE - JSON', 'INCREMENTAL - RECORD ID', NULL, 'CUSTOMER SUPPORT DATA FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

-- UBER
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('UBER', 'FLAT FILE - XML', 'FULL REFRESH - TIMESTAMP', NULL, 'CUSTOMER SUPPORT DATA FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

-- AT & T
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATA_LOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('AT&T', 'FLAT FILE - CSV', 'FULL REFRESH', NULL, 'CUSTOMER SUPPORT DATA FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 2: CSD_SUPPORT_AREAS
-- AMAZON
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ORDER ISSUES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PRODUCT INQUIRIES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SHIPPING & DELIVERY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ACCOUNT & SECURITY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('RETURNS & REFUNDS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PRIME MEMBERSHIP', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('MARKETPLACE & THIRD-PARTY SELLERS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', TRUE, NOW(), '2999-12-31');

COMMIT;


-- UBER
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('RIDE ISSUES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DRIVER/PASSENGER CONCERNS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SAFETY & SECURITY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ACCOUNT & PROFILE MANAGEMENT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PROMOTIONS & DISCOUNT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DRIVER SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('UBER EATS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ACCESIBILITY SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', TRUE, NOW(), '2999-12-31');

COMMIT;


-- AT & T
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ACCOUNT MANAGEMENT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SUPPORT OUTAGES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('NEW CUSTOMER ONBOARDING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('MOBILE & WIRELESS SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('HOME SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SECURITY & PRIVACY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BUSINESS SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('LOYALTY & RETENTIONS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 3: CSD_AGENTS
-- AMAZON
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('JOHN', 'A.', 'DOE', 'JDOE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('JANE', 'B.', 'SMITH', 'JSMITH', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ALICE', 'C.', 'JOHNSON', 'AJOHNSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BOB', 'D.', 'WILLIAMS', 'BWILLIAMS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CHARLIE', 'E.', 'BROWN', 'CBROWN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DAVID', 'F.', 'JONES', 'DJONES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('EVE', 'G.', 'GARCIA', 'EGARCIA', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FRANK', 'H.', 'MARTINEZ', 'FMARTINEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('GRACE', 'I.', 'HERNANDEZ', 'GHERNANDEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('HANK', 'J.', 'LOPEZ', 'HLOPEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), TRUE, NOW(), '2999-12-31');

COMMIT;


-- UBER
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('IVY', 'K.', 'GONZALEZ', 'IGONZALEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('JACK', 'L.', 'WILSON', 'JWILSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('KARA', 'M.', 'ANDERSON', 'KANDERSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('LEO', 'N.', 'THOMAS', 'LTHOMAS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('MIA', 'O.', 'TAYLOR', 'MTAYLOR', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('NATE', 'P.', 'MOORE', 'NMOORE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('OLIVIA', 'Q.', 'JACKSON', 'OJACKSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PAUL', 'R.', 'WHITE', 'PWHITE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('QUINN', 'S.', 'HARRIS', 'QHARRIS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('RYAN', 'T.', 'MARTIN', 'RMARTIN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), TRUE, NOW(), '2999-12-31');

COMMIT;


-- AT & T
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SARA', 'U.', 'THOMPSON', 'STHOMPSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TOM', 'V.', 'GARCIA', 'TGARCIA', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('UMA', 'W.', 'MARTINEZ', 'UMARTINEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('VICTOR', 'X.', 'HERNANDEZ', 'VHERNANDEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('WENDY', 'Y.', 'LOPEZ', 'WLOPEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('XANDER', 'Z.', 'GONZALEZ', 'XGONZALEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('YARA', 'A.', 'WILSON', 'YWILSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ZANE', 'B.', 'ANDERSON', 'ZANDERSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ABBY', 'C.', 'THOMAS', 'ATHOMAS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('EDGAR', 'D.', 'JONES', 'EJONES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 4: CSD_CUSTOMER_TYPES
-- AMAZON
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FIRST-TIME SHOPPER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FREQUENT BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PRIME MEMBER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('HIGH-SPENDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BUDGET SHOPPER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BUSINESS BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TECH-SAVVY BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('GIFT GIVER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('RETURNS & REFUND SEEKER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('COMPLAINT-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;


-- UBER
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FIRST-TIME RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FREQUENT RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('COMMUTER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TRAVELER/TOURIST', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('UBER EATS CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CORPORATE RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DRIVER-PARTNER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PROMO-SEEKER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PROMO-SEEKER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SAFETY-CONSCIOUS RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('ACCESSIBILITY-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;


-- AT & T
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('NEW CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('LONG-TERM CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('LONG-TERM CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('TECH-SAVVY USER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('SENIOR CITIZEN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BUSINESS OWNER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FAMILY PLAN MANAGER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('FREQUENT TRAVELER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('BUDGET-CONSCIOUS CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('HEAVY DATA USER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DEVICE ENTHUSIAST', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 5: CSD_TABLE_TYPES
INSERT INTO CSD_TABLE_TYPES (TABLE_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DATA MART TABLE', 'TABLE THAT STORES ACTUAL DATA FOR WHICH THE DATABASE HAS BEEN CREATED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_TYPES (TABLE_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DATA STANDARD TABLE', 'TABLE THAT DEFINES THE STANDARD VALUES FOR A COLUMN OF THE DATA MART TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_TYPES (TABLE_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DATA AUDIT TABLE', 'TABLE THAT STORES AUDIT INFORMATION OF SPECIFIC ACTIONS ON DATA MART TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_TYPES (TABLE_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('DATABASE INFORMATION TABLE', 'TABLE THAT STORES THE DATABASE RELATED INFORMATION', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 6: CSD_TABLE_LOAD_TYPES
INSERT INTO CSD_TABLE_LOAD_TYPES (TABLE_LOAD_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('PYSPARK ETL', 'THE TABLE SHALL BE LOADED USING A PYSPARK ETL FLOW', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_LOAD_TYPES (TABLE_LOAD_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('MANUAL DML', 'THE TABLE SHALL BE LOADED USING A DML STATEMENT MANUALLY', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 7: CSD_DATA_DICTIONARY
-- AMAZON
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RECORD_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (UNIQUE)', 'PRIMARY KEY OF THE SUPPORT DATA', '1', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (CAN REPEAT)', 'UNIQUE IDENTIFIER FOR AN INTERACTION', '1', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT_CATEGORY', 'STRING', '"ORDER ISSUES", "PRODUCT INQUIRIES", "SHIPPING & DELIVERY", "ACCOUNT & SECURITY", "PAYMENTS & BILLING", "RETURNS & REFUNDS", "TECHNICAL SUPPORT", "PROMOTIONS & DISCOUNTS", "PRIME MEMBERSHIP", "MARKETPLACE & THIRD-PARTY SELLERS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ORDER ISSUES', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'AGENT_PSEUDO_NAME', 'STRING', '"JDOE", "JSMITH", "AJOHNSON", "BWILLIAMS", "CBROWN", "DJONES", "EGARCIA", "FMARTINEZ", "GHERNANDEZ", "HLOPEZ"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'JDOE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CONTACT_DATE', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE OF THE INTERATION IN DD/MM/YYYY HH:MI:SS FORMAT', '01/01/2021 00:00:00', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_STATUS', 'STRING', '"COMPLETED", "DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'COMPLETED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'TYPE_OF_CUSTOMER', 'STRING', '"FIRST-TIME SHOPPER", "FREQUENT BUYER", "PRIME MEMBER", "HIGH-SPENDER", "BUDGET SHOPPER", "BUSINESS BUYER", "TECH-SAVVY BUYER", "GIFT GIVER", "RETURNS & REFUND SEEKER", "COMPLAINT-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'FIRST-TIME SHOPPER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_DURATION', 'INTEGER', 'POSITIVE INTEGERS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN SECONDS', '120', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'TOTAL_TIME', 'INTEGER', 'POSITIVE INTEGERS', 'TOTAL TIME TAKEN TO COMPLETE THE INTERACTION AND ANY WORK RELATED TO INTERACTION AFTER CALL IN SECONDS', '150', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'STATUS_OF_CUSTOMER_INCIDENT', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RESOLVED_IN_FIRST_CONTACT', 'STRING', '"YES", "NO"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', 'YES', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SOLUTION_TYPE', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RATING', 'INTEGER', '1 - 10', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '10', TRUE, NOW(), '2999-12-31');

COMMIT;


-- UBER
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED VALUE', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CONTACT_REGARDING', 'STRING', '"RIDE ISSUES", "DRIVER/PASSENGER CONCERNS", "PAYMENTS & BILLING", "SAFETY & SECURITY", "ACCOUNT & PROFILE MANAGEMENT", "PROMOTIONS & DISCOUNT", "DRIVER SUPPORT", "TECHNICAL SUPPORT", "UBER EATS", "ACCESIBILITY SUPPORT"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'RIDE ISSUES', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'AGENT_CODE', 'STRING', '"IGONZALEZ", "JWILSON", "KANDERSON", "LTHOMAS", "MTAYLOR", "NMOORE", "OJACKSON", "PWHITE", "QHARRIS", "RMARTIN"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'IGONZALEZ', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'DATE_OF_INTERACTION', 'DATE', 'DATES AFTER 2021 JAN', 'DATE IN YYYYMMDD FORMAT', '20210401', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'STATUS_OF_INTERACTION', 'STRING', '"INTERACTION COMPLETED", "CUSTOMER DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'INTERACTION COMPLETED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TYPE_OF_INTERACTION', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CHAT', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER_TYPE', 'STRING', '"FIRST-TIME RIDER", "FREQUENT RIDER", "COMMUTER", "TRAVELER/TOURIST", "UBER EATS CUSTOMER", "CORPORATE RIDER", "DRIVER-PARTNER", "PROMO-SEEKER", "SAFETY-CONSCIOUS RIDER", "ACCESSIBILITY-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'PROMO-SEEKER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CONTACT_DURATION', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN TIMESTAMP FORMAT', '00:02:00', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'AFTER_CONTACT_WORK_TIME', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN TIMESTAMP FORMAT', '00:01:00', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'INCIDENT_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'FIRST_CONTACT_SOLVE', 'BOOLEAN', '"TRUE", "FALSE"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', 'TRUE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TYPE_OF_RESOLUTION', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT_RATING', 'INTEGER', '1 - 5', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '5', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TIME_STAMP', 'TIMESTAMP', 'TIMESTAMP VALUES', 'TIMESTAMP OF THE RECORD CREATION', '01/01/2024 00:00:00', TRUE, NOW(), '2999-12-31');

COMMIT;


-- AT & T
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TICKET_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED INTEGER VALUES', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT_CATEGORY', 'STRING', '"ACCOUNT MANAGEMENT", "TECHNICAL SUPPORT", "SUPPORT OUTAGES", "NEW CUSTOMER ONBOARDING", "MOBILE & WIRELESS SERVICES", "HOME SERVICES", "PROMOTIONS & DISCOUNTS", "SECURITY & PRIVACY", "BUSINESS SERVICES", "LOYALTY & RETENTIONS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ACCOUNT MANAGEMENT', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'AGENT_NAME', 'STRING', '"STHOMPSON", "TGARCIA", "UMARTINEZ", "VHERNANDEZ", "WLOPEZ", "XGONZALEZ", "YWILSON", "ZANDERSON", "ATHOMAS", "EDJONES"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'STHOMPSON', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'DATE_OF_CALL', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE IN MMDDYYYYHHMISS FORMAT', '01012024000000', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CALL_STATUS', 'STRING', '"CALL COMPLETED", "CALL DROPPED", "CALL TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'CALL COMPLETED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CALL_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TYPE_OF_CUSTOMER', 'STRING', '"NEW CUSTOMER", "LONG-TERM CUSTOMER", "TECH-SAVVY USER", "SENIOR CITIZEN", "BUSINESS OWNER", "FAMILY PLAN MANAGER", "FREQUENT TRAVELER", "BUDGET-CONSCIOUS CUSTOMER", "HEAVY DATA USER", "DEVICE ENTHUSIAST"', 'INTERNAL CUSTOMER TYPE', 'NEW CUSTOMER', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'DURATION', 'INTEGER', 'POSTIVE INTEGER', 'DURATION OF THE INTERACTION WITH CUSTOMER IN TIMESTAMP FORMAT', '120', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'WORK_TIME', 'INTEGER', 'POSTIVE INTEGER', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN TIMESTAMP FORMAT', '30', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TICKET_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RESOLVED_IN_FIRST_CONTACT', 'INTEGER', '1, 0', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', '1', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RESOLUTION_CATEGORY', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RATING', 'STRING', '"WORST", "BAD", "NEUTRAL", "GOOD", "BEST"', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', 'BEST', TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 9: CSD_TABLE_NAMES
INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_SOURCES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SOURCES THAT ARE BEING USED IN THE DATA MART', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_SUPPORT_AREAS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SUPPORT AREAS FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_AGENTS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF AGENT NAMES FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_CUSTOMER_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF CUSTOMER TYPES FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_TABLE_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TYPES OF TABLES PRESENT IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_TABLE_LOAD_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON HOW A TABLE GETS LOADED WITH DATA', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_DATA_DICTIONARY', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE DATA RECEIVED FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_DATA_LOADS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA AUDIT TABLE'), 'TABLE TO STORE THE INFORMATION OF EACH PYSPARK LOAD EXECUTED', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'PYSPARK ETL'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_TABLE_NAMES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TABLES IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_TABLE_COLUMNS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE COLUMNS OF THE TABLES IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_DATA_MART', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA MART TABLE'), 'TABLE TO STORE THE ACTUAL DATA ON WHICH DASHBOARDS ARE TO BE CREATED', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ('CSD_TRANSFORMATIONS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE TRANSFORMATIONS THAT HAS TO BE APPLIED ON SOURCE DATA BEFORE STORING IT IN DM TABLE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), TRUE, NOW(), '2999-12-31');

COMMIT;


-- TABLE 10: CSD_TABLE_COLUMNS
INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'SOURCE_ID', 'INTEGER', NULL, 'STORES THE PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'SOURCE_NAME', 'VARCHAR', 255, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'SOURCE_FILE_TYPE', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'DATA_LOAD_STRATEGY', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'LAST_LOADED_RECORD_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SOURCES'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'SUPPORT_AREA_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'SUPPORT_AREA_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_SUPPORT_AREAS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'AGENT_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'FIRST_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'MIDDLE_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'LAST_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'PSEUDO_CODE', 'VARCHAR', 255, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_AGENTS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'CUSTOMER_TYPE_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'CUSTOMER_TYPE_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_CUSTOMER_TYPES'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_TYPES'), 'TABLE_TYPE_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'TABLE_TYPE_NAME', 'VARCHAR', 255, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'TABLE_LOAD_TYPE_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'TABLE_LOAD_TYPE_NAME', 'VARCHAR', 255, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'DATA_DICTIONARY_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'FIELD_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'DATA_TYPE', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'VALUES_ALLOWED', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'EXAMPLE', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_DICTIONARY'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'DATA_LOAD_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'LOAD_START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'LOAD_END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'TOTAL_UPSERT_COUNT', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'VALID_COUNT', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'INVALID_COUNT', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'DATA_VALID_PERCENTAGE', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_LOADS'), 'LOAD_DURATION', 'TIMESTAMP', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'TABLE_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'TABLE_NAME', 'VARCHAR', 255, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'TABLE_TYPE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'TABLE_LOAD_TYPE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_NAMES'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'TABLE_COLUMN_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'TABLE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'COLUMN_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'DATA_TYPE', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'FIELD_LENGTH', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'DESCRIPTION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TABLE_COLUMNS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'CSD_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'SOURCE_SYSTEM_IDENTIFIER', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'AGENT_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'INTERACTION_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'SUPPORT_AREA_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'INTERACTION_STATUS', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'INTERACTION_TYPE', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'CUSTOMER_TYPE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'HANDLE_TIME', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'WORK_TIME', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'FIRST_CONTACT_RESOLUTION', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'QUERY_STATUS', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'CUSTOMER_RATING', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'SOURCE_HASH_KEY', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'DATA_LOAD_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'IS_VALID_DATA', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_DATA_MART'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'TRANSFORMATION_ID', 'INTEGER', NULL, 'PRIMARY KEY OF THE TABLE', TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'SOURCE_ID', 'INTEGER', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'SOURCE_COLUMN_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'TARGET_COLUMN_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'PYSPARK_EXPRESSION', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'TARGET_TABLE_NAME', 'TEXT', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'ACTIVE_FLAG', 'BOOLEAN', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'START_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;

INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES ((SELECT TABLE_ID FROM CSD_TABLE_NAMES WHERE TABLE_NAME = 'CSD_TRANSFORMATIONS'), 'END_DATE', 'DATETIME', NULL, NULL, TRUE, NOW(), '2999-12-31');

COMMIT;
